### ISSUE TITLE
Retries aborting: Probed points range is increasing.

### ISSUE THREAD

**Issue by S1mone01** [Bully85/Sovol-SV04-Klipper#10]
I followed the entire installation for my Sovol sv04 but when I try to print any object and i get the following error: 
Retries aborting: Probed points range is increasing.

**Comment by Bully85** [comment]
Do you change the z part in Printer.cfg for gd chip?

**Comment by S1mone01** [comment]
I just tried to change the settings from printer.cfg but now I get the error: BLTouch failed to deploy

**Comment by Bully85** [comment]
Great
