### ISSUE TITLE
Transfer macros and settings

### ISSUE THREAD

**Issue by RagDollino** [Bully85/Sovol-SV04-Klipper#28]
Hello, greetings from Argentina.

I have an idex printer with the same print dimensions running klipper, and I wanted to test your profile for idex modes, but I have the problem that when trying to start a print in copy or mirror mode, the "extruder 2" does not move in the x axis, It extrudes normally like 1... but it does not move in said axis, could you give me a clue on how to solve it? Thanks in advance

**Comment by Bully85** [comment]
Can you give me more information what printer ist? Which board. How work the gantry

**Comment by RagDollino** [comment]
I am with a tenlog D3P, with the stock 8-bit board, with an ATMEGA2560
