### ISSUE TITLE
Problem with toolchange

### ISSUE THREAD

**Issue by RagDollino** [Bully85/Sovol-SV04-Klipper#29]
Doing a dual printing, when changing the tool, it raises 2mm as the macro says, but when the second extruder enters the first layer it prints in the air, then it lowers the 2mm for the next layer or when it has a travel without printing and it continues printing normally, at that moment if what it prints in the air is very large it ruins the entire piece, sorry by my english, its not my native language.

**Comment by Bully85** [comment]
In my discord in international channel was the same problem can go on it maybe its helpful

**Comment by Bully85** [comment]
![image](https://github.com/Bully85/Sovol-SV04-Klipper/assets/67374316/0089a39e-a10f-440b-a89d-403253c847c4)

Can you try this
