### ISSUE TITLE
Is this good to use with sonic pad?

### ISSUE THREAD

**Issue by scuba1976** [Bully85/Sovol-SV04-Klipper#3]
Is this good to use with sonic pad? Is it possible to use all sv04 function on sonic pad?

**Comment by Bully85** [comment]
For use this you must choose my repo. At the moment sonic pad do not support to change the repo sorry

**Comment by scuba1976** [comment]
Dear friend, i tried to do all the steps with raspberry 3b+. but i cannot connect to the printer. which firmware i have to use? there are two file.
I just need to copy all .cfg in config?
thanks

**Comment by scuba1976** [comment]
Hello, i need you help. I install everything on my sv04. i have GD32F303, but z axis doesn't work. what i make mistake?
thanks

**Comment by Bully85** [comment]
Do you change the z sector in printer.cfg

**Comment by scuba1976** [comment]
Hello, i'm sorry to bore you. I success in all the steps and i start to print. The problem is that, after z tilt calibration with right extruder, it seams to start printing with left extruder. Can you help me? thanks

**Comment by Funkelfetisch** [comment]
reopening this, anybody checked out:

https://github.com/smwoodward/Sonic-Pad-Updates/blob/main/root_access/Root

yet?
