### ISSUE TITLE
Unable to connect printer

### ISSUE THREAD

**Issue by ginwer7619** [Bully85/Sovol-SV04-Klipper#35]
Hello, I followed the installation like descriptor but I am unable to connect the printer to Klipper. I always get the error mcu 'mcu': Unable to connect. I tried several cables, reinstalled several times everything but impossible to connect the printer.
I use a Raspberry Pi 4B with 7" TFT. On my Ender3 Neo there is no problem.
Where to find a solution for this connection problem.
Thank you

**Comment by Bully85** [comment]
Do you install the mcu for pi?

https://www.klipper3d.org/Measuring_Resonances.html

https://www.klipper3d.org/RPi_microcontroller.html

**Comment by ginwer7619** [comment]
Yes, I follow the install, no errors but unable to connect, always the mcu error and no serial device with. Always the message  ls: cannot access '/dev/serial/by-path/*': No such file or directory 
I have also the info Unofficial remote url: https://github.com/Bully85/klipper in Klipper

**Comment by Bully85** [comment]
After flash the firmware rename it from bin to cur?

**Comment by ginwer7619** [comment]
Problem solved after isolating VCC pin on USB cable connection was made immediately.
Thanks

**Comment by Bully85** [comment]
Thanks for feedback
