### ISSUE TITLE
Kalibrierungswürfel

### ISSUE THREAD

**Issue by ginwer7619** [Bully85/Sovol-SV04-Klipper#36]
Hallo, ich habe den Kalibrierungswürfel gedruckt und eine Abweichung von 3,97mm. Nur finde ich nicht raus wo ich die +3,9 eingeben muss um die Abweichung zu korrigieren. 
Sonst scheint alles zu funktionieren. 
Vielen Dank für Ihre Hilfe. 
Mit freundlichen Grüßen.

**Comment by Bully85** [comment]
Es gibt das xy macro da gibst du es ein aber Achtung entweder x oder y sind + und - vertauscht einfach ausprobieren

**Comment by ginwer7619** [comment]
Ist das im idex_mode.cfg unter
[gcode_macro DC_VARS]
# Offset coordinates for dual_carriage
variable_offset_x: 0
Gebe ich hier die abweichung ein. En xy macro habe ich nicht.

**Comment by ginwer7619** [comment]
Hallo Habe das Problem gelöst, xy macro gefunden. Druck ist jetzt perfekt. Jedoch habe ich ein anderen Problem. Im copy mode läuft alles perfekt bis zum Druckbeginn, der Druck fängt an jedoch ohne aufheizen der Düsen und des Bettes.
Ich benutze Prusaslicer auf MAC, letzte version und das Prusaprofil  aus Sovol-SV04-Klipper-main. Vielen Dank im Voraus

**Comment by Bully85** [comment]
Schau dir mal deinen G. Code als Textdatei an. Ob die Temperaturen überhaupt von prusa übermittelt werden?

**Comment by ginwer7619** [comment]
Hallo, Ja steht drin
;TYPE:Custom
M190 S0
M109 S0
G28 X
SET_DUAL_CARRIAGE CARRIAGE=1 MODE=COPY
START_PRINT EXTRUDER=0 EXTRUDERS=2 EXTRUDER_TEMP=210 EXTRUDER1_TEMP=210 BED_TEMP=60 
AREA_START=29.7633,79.7414 AREA_END=113.206,129.259
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0

**Comment by Bully85** [comment]
Hast du irgendwas an den cfg Dateien geändert?

**Comment by ginwer7619** [comment]
Nein alles übernommen wie runtergeladen. Könnte höchstens Prusa löschen und neu installieren. Dort hatte ich verschiedene änderungen gemacht für meine umgebaute creality. Könnte das Problem davon kommen.

**Comment by Bully85** [comment]
Hast du discord? Am besten schickst du mir mal den gcode und ich schau mal. Ich glaube nicht unbedingt dass deine Änderungen bei anderen Druckern hier zu trage kommen aber ausschließen kann ich es nicht wichtig ist zu wissen was im gcode steht.

Hast du auch die aktuellen cfg und prusa Profile aus meinem Release?

**Comment by ginwer7619** [comment]
Discord habe ich nicht. cfg und Prusa profile sind as dem release.

**Comment by Bully85** [comment]
Was hast du als gcode flavor in prusa

**Comment by ginwer7619** [comment]
Marlin2.
Habe soeben was im mirror mode versucht, dort klappt es. Werde Prusa neu installieren und morgen nochmal versuchen im copy mode.

**Comment by Bully85** [comment]
Ok halt mich auf den Stand

**Comment by ginwer7619** [comment]
Hallo, nach Neuinstallation von Prusa klappt es jetzt. Das einzige was ist, die Prime Line ist mir etwas zu weit im Bett. Wo kann ich den Abstand verringern. Ich hatte das normalerweise im G-Code auf 5mm stehen (G1 X5.0 Y20 Z0.3 F5000.0 ; Move to start position
G1 X5.0 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X5.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X5.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line)
ist aber jetzt auf etwa 15mm.
Im Start_End macro steht nur PRIME_LINE habe aber nicht heraus gefunden wo man die Angaben dazu machen kann.

**Comment by Bully85** [comment]
In macro.cfg ist es

**Comment by ginwer7619** [comment]
Habs gefunden, Danke. Da hatte ich natürlich nicht gekuckt. Noch eine Frage zur Anzeige, dort ist die Anzeige der Ventilatoren nicht komplett, ist das auch irgendwo einstellbar.
![IMG_3795](https://github.com/Bully85/Sovol-SV04-Klipper/assets/95778839/06aa4473-33ed-4190-92f4-f1fa6b7da2a0)

**Comment by Bully85** [comment]
Im Copy Mode und Miro Mode gibt es keine zwei

**Comment by ginwer7619** [comment]
Was bedeutet dann das 2te F: 5. Der Ventilator vom rechten Druckkopf läuft aktuell mit 50% daher die Annahme dass da der Schluss fehlt in der Anzeige.

**Comment by ginwer7619** [comment]
Ich habe auch unter Klipper sie Anzeige Unofficial remote url: https://github.com/Bully85/klipper Wie kann ich dies beheben. In Kiauh habe ich die Datei geändert wie Beschrieben.

**Comment by Bully85** [comment]
Okay, scheint dass du recht hast. Da wird was abgeschnitten sein muss ich heute Abend mal bei mir schauen wie es aussieht

**Comment by Bully85** [comment]
Das kannst du beheben, indem du Softrepair machst

**Comment by ginwer7619** [comment]
Hallo, noch ein Problem. Ich drucke aktuell nur mit dem rechten Druckkopf. Dabei zeigt der Bildschirm Layer und Filament komplett daneben an. Aktuell müsste er irgendwo um Layer 80 sein. Ist das auch irgendwo zu beheben?
<img width="480" alt="Screenshot 2024-02-16 at 17 17 09" src="https://github.com/Bully85/Sovol-SV04-Klipper/assets/95778839/d594a86b-c6d0-4871-a108-7acf1c483231">

**Comment by Bully85** [comment]
Mit dem Recht im Kopf in Dual Modus oder Rechtsmodus

**Comment by ginwer7619** [comment]
Hallo, gibt es ein Problem im copy mode mit Support's. Wenn ich im copy mode drucken möchte mit support drucken beide Köpfe vom ersten Layer den Support und dann geht der linke Kopf in Park Stellung und der rechte fährt auf die linke Druckseite (original) und fängt an zu drucken jedoch ohne Materialvorschub. Beide Düsen und Bett bleiben auf Drucktemperatur. Drucke ich das gleiche Teil zum Test ohne Support geht es. Slicer ist Prusa mit Ihren Einstellungen
Vielen Dank

**Comment by ginwer7619** [comment]
> Okay, scheint dass du recht hast. Da wird was abgeschnitten sein muss ich heute Abend mal bei mir schauen wie es aussieht

Hallo, schon was raus gefunden mit den abgeschnittenen Anzeigen?

**Comment by Bully85** [comment]
Bin im Moment mit meiner Arbeit sehr eingespannt. Sobald ich Luft finde, schaue ich nach allen Problemen, die bis jetzt auftreten.

**Comment by ginwer7619** [comment]
Hallo, ich habe ein Problem nachdem input shapper gemacht wurde. Beim Drucken wird Home und Z-Tilt normal ausgeführt jedoch beim Bed Mesh (Komplet oder Area) kommt nach der 1ten Messstelle eine Fehlermeldung BLTouch failed to deploy danach Failed to verify BLTouch probe is raised; retrying. und nochmal BLTouch failed to deploy und der Drucker bleibt stehen. Nach der ersten Messung zieht Bltouch den Messstift zurück. Klammere ich in Printer.cfg die input-shaper Zeilen aus geht wieder alles normal. Muss da noch was irgendwo geändert werden dass BlTouch keinen Fehler erzeugt? Alle Dateien sind original. Vielen Dank.

**Comment by ginwer7619** [comment]
Hallo, Bed Mesh Problem gelöst. Habe probe_with_touch_mode: True unter bltouch eingefügt und schon klappt's.
Mit freundlichen Grüßen.

**Comment by ginwer7619** [comment]
> > Okay, scheint dass du recht hast. Da wird was abgeschnitten sein muss ich heute Abend mal bei mir schauen wie es aussieht
> 
> Hallo, schon was raus gefunden mit den abgeschnittenen Anzeigen?

Hallo, Gibts schon was neues betreffend der abgeschnittenen Anzeige (meine Nachricht vom 16/02/24)?

Mit freundlichen Grüßen.

**Comment by Bully85** [comment]
Hast du mittlerweile mal Klipperscreen geupdated?

**Comment by ginwer7619** [comment]
Hallo,Ja alles auf dem letzten Stand. Le 25 juil. 2024 à 19:32, Bully85 ***@***.***> a écrit :﻿
Hast du mittlerweile mal Klipperscreen geupdated?
